#!/bin/bash

PROGNAME=$0

if [ -z "$1" ]; then
  echo "No input file passed.

Example usage: $PROGNAME file.md"
  exit 2
fi

FILE=$1

TITLE=$(sed '1q;d' $FILE)
DESCRIPTION=$(sed '3q;d' $FILE)
SLUG=$(sed '5q;d' $FILE)
PUB_DATE=$(date +"%a, %d %b %Y %H:%M:%S %z")
BODY=$(cat $FILE | tail --lines=+7 | pandoc --to html)

generate_html() {
  echo "generating html..." >&2
  cat << EOF
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>$TITLE - Roberto Tonino</title>

    <meta name="description" property="og:description" content="$DESCRIPTION">
    <meta name="author" content="Roberto Tonino">
    <link rel="canonical" href="https://www.robertotonino.com/$SLUG">

    <meta property="og:title" content="$TITLE">
    <meta property="og:url" content="https://www.robertotonino.com/$SLUG">
    <meta property="og:type" content="article">
    <meta property="og:image" content="">
    <meta property="og:image:alt" content="">

    <meta name="twitter:card" content="summary_large_image">
    <meta property="twitter:domain" content="robertotonino.com">
    <meta property="twitter:url" content="https://www.robertotonino.com/$SLUG">
    <meta name="twitter:title" content="$TITLE">
    <meta name="twitter:description" content="$DESCRIPTION">
    <meta name="twitter:image" content="">

    <script type="application/ld+json">
      {
        "@context": "https://schema.org",
        "@type": "WebSite",
        "name": "Roberto Tonino",
        "url": "https://robertotonino.com"
      }
    </script>

    <link rel="stylesheet" href="./index.css">
    <link href="/favicon-light.png" rel="icon" media="(prefers-color-scheme: light)">
    <link href="/favicon-dark.png" rel="icon" media="(prefers-color-scheme: dark)">
    <link href="/favicon-light.png" type="image/x-icon" rel="shortcut icon" media="(prefers-color-scheme: light)">
    <link href="/favicon-dark.png" type="image/x-icon" rel="shortcut icon" media="(prefers-color-scheme: dark)">
    <link href="/favicon-light.png" type="image/x-icon" rel="apple-touch-icon" media="(prefers-color-scheme: light)">
    <link href="/favicon-dark.png" type="image/x-icon" rel="apple-touch-icon" media="(prefers-color-scheme: dark)">
    <!-- Cloudflare Web Analytics --><script defer src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{"token": "776ec8b3b80340d38108e9adbe35d3ca"}'></script><!-- End Cloudflare Web Analytics -->
  </head>

  <body>
    <aside id="support-ukraine">
      <a href="https://u24.gov.ua/">
        <img src="https://flagcdn.com/16x12/ua.png" srcset="https://flagcdn.com/32x24/ua.png 2x, https://flagcdn.com/48x36/ua.png 3x" width="16" height="12" alt="Ukraine flag">&nbsp;Support Ukraine by donating here. Thank you!&nbsp;<img src="https://flagcdn.com/16x12/ua.png" srcset="https://flagcdn.com/32x24/ua.png 2x, https://flagcdn.com/48x36/ua.png 3x" width="16" height="12" alt="Ukraine flag">
      </a>
    </aside>
    <main>
      <header>
        <p id="title"><a href="/">Roberto Tonino</a></p>
      </header>

      <article itemscope itemtype="http://schema.org/BlogPosting">
        <link itemscope itemprop="author" itemtype="https://schema.org/Person">
          <meta itemprop="name" content="Roberto Tonino">
          <meta itemprop="url" content="https://www.robertotonino.com">
        </span>

        <hgroup>
          <h1 itemprop="name headline">$TITLE</h1>

          <p>
            <time datetime="$(date -I)" itemprop="datePublished">$(date +"%B %Y")</time>
          </p>
        </hgroup>

        <section itemprop="articleBody">
$BODY
        </section>

      </article>
    </main>
  </body>

</html>
EOF
}

generate_feed() {
  echo "generating feed..." >&2
  cat << EOF
<item>
  <title>$TITLE</title>
  <guid>https://www.robertotonino.com/$SLUG</guid>
  <link>https://www.robertotonino.com/$SLUG</link>
  <description>$DESCRIPTION</description>
  <!--<pubDate>Tue, 11 Jun 2024 21:11:36 +0200</pubDate>-->
  <pubDate>$PUB_DATE</pubDate>
</item>
EOF
}

generate_html > POST_TO_MOVE.html
generate_feed > FEED_TO_MOVE.xml
